{"name": "Попытка логина с некорректными данными", "status": "passed", "steps": [{"name": "Логин юзера", "status": "passed", "parameters": [{"name": "user_data", "value": "{'email': 'wrong@yandex.ru', 'password': 'wrongpassword'}"}], "start": 1720369573709, "stop": 1720369573996}], "start": 1720369573709, "stop": 1720369573996, "uuid": "a9cacf60-a0d5-4d21-89d5-6ab999626ba7", "historyId": "306f11a41a6e9a9e4b4aa95aea12075d", "testCaseId": "306f11a41a6e9a9e4b4aa95aea12075d", "fullName": "tests.test_auth#test_login_user_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "0000NBB03CJLVCF"}, {"name": "thread", "value": "47299-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}